package shell

import (
	"encoding/json"
	"errors"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"sync"
	"syscall"
	"time"
	"unsafe"

	webview2 "github.com/jchv/go-webview2"
	"golang.org/x/sys/windows/registry"
)

var (
	user32                  = syscall.NewLazyDLL("user32.dll")
	procMessageBoxW         = user32.NewProc("MessageBoxW")
	procGetDpiForSystem     = user32.NewProc("GetDpiForSystem")
	procGetWindowPlacement  = user32.NewProc("GetWindowPlacement")
	procSetWindowPlacement  = user32.NewProc("SetWindowPlacement")
	procMonitorFromRect     = user32.NewProc("MonitorFromRect")
	dwmapi                  = syscall.NewLazyDLL("dwmapi.dll")
	procSetWindowAttribute  = dwmapi.NewProc("DwmSetWindowAttribute")
)

const (
	mbIconError = 0x10

	dwmwaUseImmersiveDarkMode = 20

	swShowNormal    = 1
	swShowMaximized = 3
)

var errNoWebView2 = errors.New("failed to create a WebView2 window (is the WebView2 runtime installed?)")

func run(opts Options) error {
	dataPath := ""

	// Keep the WebView2 profile out of the install directory.
	if dir, err := os.UserCacheDir(); err == nil {
		dataPath = filepath.Join(dir, opts.Title)
	}

	base, _ := url.Parse(opts.URL)

	w := webview2.NewWithOptions(webview2.WebViewOptions{
		Debug:     opts.Debug,
		DataPath:  dataPath,
		AutoFocus: true,

		WindowOptions: webview2.WindowOptions{
			Title:  opts.Title,
			Width:  uint(scaleForDPI(opts.Width)),
			Height: uint(scaleForDPI(opts.Height)),
			IconId: 1, // RT_GROUP_ICON "#1" generated by `go tool appbundle`
			Center: true,
		},
	})

	if w == nil {
		fatalDialog(opts.Title, "Failed to create a WebView2 window.\n\nThe WebView2 Runtime may not be installed. Get it from:\nhttps://developer.microsoft.com/microsoft-edge/webview2/")
		return errNoWebView2
	}

	defer w.Destroy()

	hwnd := uintptr(w.Window())

	if opts.MinWidth > 0 || opts.MinHeight > 0 {
		w.SetSize(scaleForDPI(opts.MinWidth), scaleForDPI(opts.MinHeight), webview2.HintMin)
	}

	applyDarkTitleBar(hwnd)

	placementPath := ""

	if dataPath != "" {
		placementPath = filepath.Join(dataPath, "window.json")
		restorePlacement(hwnd, placementPath)
	}

	// WebView2 opens target="_blank" links (and middle-clicks on them) in a
	// bare popup window by default; route them to the default browser
	// instead, unless they're same-origin, in which case just navigate here.
	w.Bind("__windowOpenExternal", func(rawURL string) { openLink(w, base, rawURL) })
	w.Init(`function shellLinkHandler(e) {
		const anchor = e.target.closest('a[target="_blank"]');
		if (anchor && anchor.href) {
			e.preventDefault();
			__windowOpenExternal(anchor.href);
		}
	}
	document.addEventListener('click', shellLinkHandler, true);
	document.addEventListener('auxclick', shellLinkHandler, true);`)

	w.Navigate(opts.URL)

	stop := trackPlacement(hwnd)

	w.Run()

	if p := stop(); p != nil && placementPath != "" {
		savePlacement(placementPath, p)
	}

	return nil
}

func openLink(w webview2.WebView, base *url.URL, rawURL string) {
	u, err := url.Parse(rawURL)

	if err != nil {
		return
	}

	if base != nil && u.Scheme == base.Scheme && u.Host == base.Host {
		w.Navigate(rawURL)
		return
	}

	// Not restricted to http(s): mirrors the macOS shell's NSWorkspace
	// openURL, which hands any scheme (mailto:, etc.) to its registered
	// handler rather than silently dropping it.
	exec.Command("rundll32", "url.dll,FileProtocolHandler", rawURL).Start()
}

func scaleForDPI(v int) int {
	dpi, _, _ := procGetDpiForSystem.Call()

	if dpi == 0 {
		return v
	}

	return int(float64(v) * float64(dpi) / 96.0)
}

// applyDarkTitleBar keeps the title bar from staying white when Windows runs
// in dark mode.
func applyDarkTitleBar(hwnd uintptr) {
	key, err := registry.OpenKey(registry.CURRENT_USER, `Software\Microsoft\Windows\CurrentVersion\Themes\Personalize`, registry.QUERY_VALUE)

	if err != nil {
		return
	}

	defer key.Close()

	light, _, err := key.GetIntegerValue("AppsUseLightTheme")

	if err != nil || light != 0 {
		return
	}

	enabled := int32(1)
	procSetWindowAttribute.Call(hwnd, dwmwaUseImmersiveDarkMode, uintptr(unsafe.Pointer(&enabled)), unsafe.Sizeof(enabled))
}

// Window placement persistence — the macOS shell gets this for free via
// setFrameAutosaveName; on Windows the placement is polled while the window
// lives (the window procedure belongs to the webview2 library, so there is
// no close hook) and written next to the WebView2 profile.

type windowRect struct {
	Left, Top, Right, Bottom int32
}

type windowPoint struct {
	X, Y int32
}

type windowPlacement struct {
	Length         uint32
	Flags          uint32
	ShowCmd        uint32
	MinPosition    windowPoint
	MaxPosition    windowPoint
	NormalPosition windowRect
}

type placement struct {
	Left      int32 `json:"left"`
	Top       int32 `json:"top"`
	Right     int32 `json:"right"`
	Bottom    int32 `json:"bottom"`
	Maximized bool  `json:"maximized"`
}

func restorePlacement(hwnd uintptr, path string) {
	data, err := os.ReadFile(path)

	if err != nil {
		return
	}

	var p placement

	if err := json.Unmarshal(data, &p); err != nil {
		return
	}

	rect := windowRect{p.Left, p.Top, p.Right, p.Bottom}

	// Skip if the saved area is on no connected monitor (unplugged display).
	if monitor, _, _ := procMonitorFromRect.Call(uintptr(unsafe.Pointer(&rect)), 0); monitor == 0 {
		return
	}

	wp := windowPlacement{
		Length:         uint32(unsafe.Sizeof(windowPlacement{})),
		ShowCmd:        swShowNormal,
		NormalPosition: rect,
	}

	if p.Maximized {
		wp.ShowCmd = swShowMaximized
	}

	procSetWindowPlacement.Call(hwnd, uintptr(unsafe.Pointer(&wp)))
}

func trackPlacement(hwnd uintptr) func() *placement {
	var mu sync.Mutex
	var last *placement

	done := make(chan struct{})

	go func() {
		ticker := time.NewTicker(time.Second)
		defer ticker.Stop()

		for {
			select {
			case <-done:
				return

			case <-ticker.C:
				wp := windowPlacement{Length: uint32(unsafe.Sizeof(windowPlacement{}))}

				if ok, _, _ := procGetWindowPlacement.Call(hwnd, uintptr(unsafe.Pointer(&wp))); ok == 0 {
					continue
				}

				mu.Lock()
				last = &placement{
					Left:      wp.NormalPosition.Left,
					Top:       wp.NormalPosition.Top,
					Right:     wp.NormalPosition.Right,
					Bottom:    wp.NormalPosition.Bottom,
					Maximized: wp.ShowCmd == swShowMaximized,
				}
				mu.Unlock()
			}
		}
	}()

	return func() *placement {
		close(done)

		mu.Lock()
		defer mu.Unlock()

		return last
	}
}

func savePlacement(path string, p *placement) {
	data, err := json.Marshal(p)

	if err != nil {
		return
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return
	}

	os.WriteFile(path, data, 0o644)
}

func fatalDialog(title, message string) {
	t, err := syscall.UTF16PtrFromString(title)

	if err != nil {
		return
	}

	m, err := syscall.UTF16PtrFromString(message)

	if err != nil {
		return
	}

	procMessageBoxW.Call(0, uintptr(unsafe.Pointer(m)), uintptr(unsafe.Pointer(t)), mbIconError)
}
